leia:
  build: .
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "localhost:80:80"

leia-test:
  build: .
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: test