leia:
  build: .
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "localhost:80:80"
  environment:
    - MIPS_IMAGE_NO_PULL=1

leia-test:
  build: .
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: test
  environment:
    - MIPS_IMAGE_NO_PULL=1